/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kaffeine.coffee.shop;

import MilkCofee.CakeItems;
import MyFrames.AddICoffeeItems;
//import MyFrames.AdminFrame;
import MilkCofee.MilkCoffeeDrinks;
import MilkCofee.NonMilkCoffeeDrinks;
import MyFrames.OrderCakeItems;
import MyFrames.OrderCoffeeItems;
import MyFrames.OrderJuiceItems;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author CHARLES JOSEPH
 */
public class KaffeineInterface extends javax.swing.JFrame {

    /**
     * Creates new form KaffeeneInterface
     */
    public KaffeineInterface() {
        initComponents();
        setdate();
        setLocationRelativeTo(null);
        showDate();
    }
    
    void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
       dateLabel.setText(s.format(d));
    }
    
    public void setdate(){
             ActionListener actiondate = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                java.util.Date mydate = new Date();
                
                timeLabel.setText(mydate.getHours()+" : "+mydate.getMinutes()+" : "+mydate.getSeconds());
                //dateLabel.setText(mydate.getDay()+" - "+mydate.getMonth()+" - "+mydate.getYear());
            }
        };
    new javax.swing.Timer(1000, actiondate).start();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu22 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu41 = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu42 = new javax.swing.JMenu();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu43 = new javax.swing.JMenu();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenu44 = new javax.swing.JMenu();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenu45 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenu46 = new javax.swing.JMenu();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu47 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu25 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu26 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu27 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu28 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu29 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu30 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu31 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu32 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu33 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        desktop.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("ADMIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        desktop.add(jButton1);
        jButton1.setBounds(740, 310, 200, 30);

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        desktop.add(timeLabel);
        timeLabel.setBounds(830, 40, 170, 40);

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        desktop.add(dateLabel);
        dateLabel.setBounds(830, 0, 170, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Images/sadadad (1000 x 714).jpg"))); // NOI18N
        desktop.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 660);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jMenu1.setText("  Main ");
        jMenu1.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Images/Actions-exit-icon (24 x 24).jpg"))); // NOI18N
        jMenuItem10.setText("Exit");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("  Menu Card ");
        jMenu2.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N

        jMenu7.setText("Coffee Drinks");

        jMenu3.setText("Milk Based Coffee Drinks");

        jMenu13.setText("Cappucino");
        jMenu13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu13ActionPerformed(evt);
            }
        });

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Images/Cappucino (188 x 126).jpg"))); // NOI18N
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem15);

        jMenu3.add(jMenu13);

        jMenu14.setText("Latte");

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Images/New folder/latte.jpg"))); // NOI18N
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem20);

        jMenu3.add(jMenu14);

        jMenu16.setText("Cafe Mocha");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Images/New folder/Caffe Mocha.jpg"))); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem2);

        jMenu3.add(jMenu16);

        jMenu17.setText("Eiskeffee");

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Images/New folder/Eiskeff.jpg"))); // NOI18N
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuItem17);

        jMenu3.add(jMenu17);

        jMenu18.setText("Galao");

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Images/New folder/Galao (132 x 116).jpg"))); // NOI18N
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu18.add(jMenuItem18);

        jMenu3.add(jMenu18);

        jMenu19.setText("Caff Marocchino");

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Images/New folder/CaffeMarocchino (225 x 149).jpg"))); // NOI18N
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu19.add(jMenuItem19);

        jMenu3.add(jMenu19);

        jMenu7.add(jMenu3);

        jMenu4.setText("Non-Milk Based Coffee Drinks");

        jMenu21.setText("Short Black");

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Images/New folder/Short+Black (200 x 133).jpg"))); // NOI18N
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem14);

        jMenu4.add(jMenu21);

        jMenu22.setText("Long Black/ Caffe Americano");

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Images/New folder/Long+Black+or+Americano (134 x 133).jpg"))); // NOI18N
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem23);

        jMenu4.add(jMenu22);

        jMenu23.setText("Ristretto");

        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Images/New folder/Ristretto (100 x 150).jpg"))); // NOI18N
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem24);

        jMenu4.add(jMenu23);

        jMenu7.add(jMenu4);

        jMenu2.add(jMenu7);

        jMenu8.setText("Juices");

        jMenu11.setText("Apple and Carrot Juice");

        jMenuItem35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Juices/Apple and Carrot Juice (129 x 150).jpg"))); // NOI18N
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem35);

        jMenu8.add(jMenu11);

        jMenu41.setText("Carrot and Orange Juice");

        jMenuItem36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Juices/Carrot and Orange Juice (150 x 100).jpg"))); // NOI18N
        jMenu41.add(jMenuItem36);

        jMenu8.add(jMenu41);

        jMenu42.setText("Fresh Strawberry Juice");

        jMenuItem37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Juices/Fresh Strawberry Juice (135 x 224).jpg"))); // NOI18N
        jMenu42.add(jMenuItem37);

        jMenu8.add(jMenu42);

        jMenu43.setText("Freshly Squeezed Orange Juice");

        jMenuItem38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Juices/Freshly Squeezed Orange Juice (150 x 112).jpg"))); // NOI18N
        jMenu43.add(jMenuItem38);

        jMenu8.add(jMenu43);

        jMenu44.setText("Pineapple and Banana Juice");

        jMenuItem39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Juices/Pineapple and Banana Juice (118 x 150).jpg"))); // NOI18N
        jMenu44.add(jMenuItem39);

        jMenu8.add(jMenu44);

        jMenu45.setText("Ripe Banana and Strawberry Juice");

        jMenuItem40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Juices/Ripe Banana and Strawberry Juice (150 x 224).jpg"))); // NOI18N
        jMenu45.add(jMenuItem40);

        jMenu8.add(jMenu45);

        jMenu46.setText("Watermelon and Cantaloupe Juice");

        jMenuItem41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Juices/Watermelon Juice with Ice (150 x 150).jpg"))); // NOI18N
        jMenu46.add(jMenuItem41);

        jMenu8.add(jMenu46);

        jMenu47.setText("Watermelon Juice with Ice");

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Juices/Watermelon and Cantaloupe Juice (147 x 150).jpg"))); // NOI18N
        jMenu47.add(jMenuItem16);

        jMenu8.add(jMenu47);

        jMenu2.add(jMenu8);

        jMenu9.setText("Cake");

        jMenu24.setText("Blueberry Buckle");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Cakes/Blueberry Buckle (198 x 132).jpg"))); // NOI18N
        jMenu24.add(jMenuItem1);

        jMenu9.add(jMenu24);

        jMenu25.setText("Carrot Cake with Cream Cheese Frosting");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Cakes/Carrot Cake with Cream Cheese Frosting (173 x 115).jpg"))); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu25.add(jMenuItem3);

        jMenu9.add(jMenu25);

        jMenu26.setText("German Chocolate Cake");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Cakes/German Chocolate Cake (182 x 121).jpg"))); // NOI18N
        jMenu26.add(jMenuItem4);

        jMenu9.add(jMenu26);

        jMenu27.setText("Ho Ho Cake");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Cakes/Ho Ho Cake (198 x 132).jpg"))); // NOI18N
        jMenu27.add(jMenuItem5);

        jMenu9.add(jMenu27);

        jMenu28.setText("Homemade Rum Cake");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Cakes/Homemade Rum Cake (184 x 275).jpg"))); // NOI18N
        jMenu28.add(jMenuItem6);

        jMenu9.add(jMenu28);

        jMenu29.setText("New York-Style Crumb Cake");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Cakes/New York-Style Crumb Cake (173 x 130).jpg"))); // NOI18N
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu29.add(jMenuItem7);

        jMenu9.add(jMenu29);

        jMenu30.setText("Peanut Butter Cup Overload Cake");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Cakes/Peanut Butter Cup Overload Cake (198 x 149).jpg"))); // NOI18N
        jMenu30.add(jMenuItem8);

        jMenu9.add(jMenu30);

        jMenu31.setText("Pumpkin Roll");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Cakes/Pumpkin Roll (198 x 297).jpg"))); // NOI18N
        jMenu31.add(jMenuItem9);

        jMenu9.add(jMenu31);

        jMenu32.setText("Snickers Cake");

        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Cakes/Snickers Cake (198 x 297).jpg"))); // NOI18N
        jMenu32.add(jMenuItem25);

        jMenu9.add(jMenu32);

        jMenu33.setText("Texas Sheet Cake");

        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffeine/coffee/shop/Cakes/Texas Sheet Cake (182 x 123).jpg"))); // NOI18N
        jMenu33.add(jMenuItem26);

        jMenu9.add(jMenu33);

        jMenu2.add(jMenu9);

        jMenuBar1.add(jMenu2);

        jMenu15.setText("  Order ");
        jMenu15.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N

        jMenuItem29.setText("Coffee");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem29);

        jMenuItem28.setText("Juice");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem28);

        jMenuItem27.setText("Cake");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem27);

        jMenuBar1.add(jMenu15);

        jMenu5.setText("  About Us");
        jMenu5.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N

        jMenuItem11.setText("Staffs");
        jMenu5.add(jMenuItem11);

        jMenu6.setText("Branches");

        jMenuItem12.setText("Colombo");
        jMenu6.add(jMenuItem12);

        jMenuItem13.setText("Kandy");
        jMenu6.add(jMenuItem13);

        jMenu5.add(jMenu6);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
       System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //        Administrative a = new Administrative();
        //        KaffeineInterface.this.setVisible(false);
        //        a.setVisible(true);
        AdminIdentification f = new AdminIdentification();

        f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        OrderCakeItems f = new OrderCakeItems();
        jLabel1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
        OrderJuiceItems f = new OrderJuiceItems();
        jLabel1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
        OrderCoffeeItems f = new OrderCoffeeItems();
        jLabel1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KaffeineInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KaffeineInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KaffeineInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KaffeineInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KaffeineInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
